package registroestudiantes;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mauricio
 */
public class form1 extends javax.swing.JFrame implements ActionListener {
   
    private static ArrayList<Alumno>arreglo= new ArrayList<>();
    
    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();
        
        cargarFicheroEnArray();
        
        botonguardar.addActionListener(this);
        botonmostrar.addActionListener(this);
        botonsalir.addActionListener(this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcarnet = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        botonmostrar = new javax.swing.JButton();
        botonsalir = new javax.swing.JButton();
        botonguardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcarrera = new javax.swing.JComboBox<>();
        txtsede = new javax.swing.JComboBox<>();
        txtcatedratico = new javax.swing.JComboBox<>();
        txtcurso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("CARNET");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 60, 60, 20);

        jLabel2.setText("NOMBRE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 100, 50, 14);

        jLabel3.setText("DIRECCION");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 140, 80, 20);

        jLabel4.setText("TELEFONO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 180, 60, 14);
        jPanel1.add(txtcarnet);
        txtcarnet.setBounds(140, 50, 330, 30);
        jPanel1.add(txtnombre);
        txtnombre.setBounds(140, 90, 330, 30);

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        jPanel1.add(txtdireccion);
        txtdireccion.setBounds(140, 130, 330, 30);
        jPanel1.add(txttelefono);
        txttelefono.setBounds(140, 170, 330, 30);

        jLabel5.setText("CORREO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 230, 60, 14);
        jPanel1.add(txtcorreo);
        txtcorreo.setBounds(140, 210, 330, 40);

        botonmostrar.setText("MOSTRAR");
        jPanel1.add(botonmostrar);
        botonmostrar.setBounds(270, 260, 90, 23);

        botonsalir.setText("SALIR");
        jPanel1.add(botonsalir);
        botonsalir.setBounds(380, 260, 100, 20);

        botonguardar.setText("GUARDAR");
        botonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarActionPerformed(evt);
            }
        });
        jPanel1.add(botonguardar);
        botonguardar.setBounds(170, 260, 90, 23);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(30, 200, 500, 300);

        jPanel3.setLayout(null);

        jLabel6.setText("CARRERA ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 20, 60, 20);

        jLabel7.setText("SEDE");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 60, 40, 20);

        jLabel8.setText("CATEDRATICO");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 100, 80, 14);

        jLabel9.setText("CURSO");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 140, 50, 10);

        txtcarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PSICOLOGIA", "INGENIERIA EN SISTEMAS", "ADMINISTRACCION", " " }));
        jPanel3.add(txtcarrera);
        txtcarrera.setBounds(90, 10, 160, 30);

        txtsede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ZACAPA", "CHIQUIMULA", "GUATEMALA", " " }));
        jPanel3.add(txtsede);
        txtsede.setBounds(90, 50, 160, 30);

        txtcatedratico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ING ROBERTO GUZMAN", "ING VINICIO PENA", "ING BENARDO LOPEZ", "LICDA KARLA CHINCHILLA" }));
        jPanel3.add(txtcatedratico);
        txtcatedratico.setBounds(90, 90, 160, 30);

        txtcurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATEMATICAS I", "PROGRAMACION II", "PROGRACION I" }));
        jPanel3.add(txtcurso);
        txtcurso.setBounds(90, 130, 160, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(140, 20, 340, 170);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 40, 560, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonguardarActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonguardar;
    private javax.swing.JButton botonmostrar;
    private javax.swing.JButton botonsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtcarnet;
    private javax.swing.JComboBox<String> txtcarrera;
    private javax.swing.JComboBox<String> txtcatedratico;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JComboBox<String> txtcurso;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JComboBox<String> txtsede;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if ( e.getSource() == botonguardar ){
            guardardatos(); // Guardar los datos introducidos en un ArrayList
        }
        
        if ( e.getSource() == botonmostrar ){
            TablaAlumnos alumnos = new TablaAlumnos();
            alumnos.setBounds(100, 100, 1000, 600); // x, y, anchura, altura
            alumnos.setArrayListAlumno(arreglo);
            alumnos.llenarTabla();
            alumnos.setVisible(true);
        }
        
        if ( e.getSource() == botonsalir ){
            guardarEnFichero();
            this.dispose();
        }
    }
    
    void guardardatos(){
        if (txtcarnet.getText().length()==0 || txtnombre.getText().length()==0 || txtdireccion.getText().length()==0 || txttelefono.getText().length()==0 || txtcorreo.getText().length()==0  ){
            System.out.print("LOS CAMPOS ESTAN VACIOS");
        }else{
            // Guarda los datos
            Alumno nuevo_alumno = new Alumno();
            
            nuevo_alumno.setCarrera ( txtcarrera.getSelectedItem().toString() );
            nuevo_alumno.setSede ( txtsede.getSelectedItem().toString() );
            nuevo_alumno.setCatedratico ( txtcatedratico.getSelectedItem().toString() );
            nuevo_alumno.setCurso ( txtcurso.getSelectedItem().toString() );
            
            nuevo_alumno.setCarnet ( txtcarnet.getText() );
            nuevo_alumno.setNombre ( txtnombre.getText() );
            nuevo_alumno.setDireccion ( txtdireccion.getText() );
            nuevo_alumno.setTelefono ( txttelefono.getText() );
            nuevo_alumno.setCorreo ( txtcorreo.getText() );
            
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
            
            arreglo.add(nuevo_alumno);
            
            // Limpiar los campos
            txtcarnet.setText("");
            txtnombre.setText("");
            txtdireccion.setText("");
            txttelefono.setText("");
            txtcorreo.setText("");
        }
    }

    private void guardarEnFichero() {
        try {
            ObjectOutputStream escribir = new ObjectOutputStream( new FileOutputStream(new File("estudiantes.txt") ));
            escribir.writeObject(arreglo); // escribimos en el fichero los campos del ArrayList 
            escribir.close(); // cerrar el objeto escribiendoFichero 
        } catch (IOException e) {
            System.out.println("No se pudo guardar.");
        }
    }
    
    private void cargarFicheroEnArray(){
        try{
            ObjectInputStream leer = new ObjectInputStream ( new FileInputStream(new File("estudiantes.txt") ));
            arreglo = (ArrayList<Alumno>) leer.readObject();
            leer.close();
        }catch( IOException | ClassNotFoundException e ){
            System.out.println("No se pudo cargar.");
        }
    }
    
    public static void setArregloGeneral(ArrayList<Alumno> lista){
        form1.arreglo = (ArrayList<Alumno>) lista.clone();
    }
}